### PR TITLE
feat: add cluster nodes rsg client ID to jx-requirements

### PR DESCRIPTION
**Pull request by Skisocks**
Adds the Client ID for the cluster nodes resource group to jx-requirements. This is needed for identifying which service principal to use when pushing containers to the registry (in the case where there are multiple principals).

https://github.com/jenkins-x/jx/issues/8580

### CODE REVIEW

**Comment by msvticket** [comment]
Same here, Tom is the man.

/cc tomhobson

**Review by tomhobson — APPROVED** [review]

**Review by tomhobson — APPROVED** [review]

**Pull request merged**
